### ISSUE TITLE
bug: pattern UI graphs disappearing

### ISSUE THREAD

**Issue by cyriltovena** [grafana/explore-logs#355] opened 2024-05-28 12:27 UTC
When switching windows or tabs all graph are disappearing.

<img width="2534" alt="image" src="https://github.com/grafana/explore-logs/assets/1053421/c3368f78-aa2e-4f87-8e10-584df63ff60a">

**Comment by gtk-grafana** [comment] 2024-06-03 18:33
I can't reproduce this, can you provide some more info @cyriltovena?

**Comment by gtk-grafana** [comment] 2024-07-01 18:13
I think this was the loki bug where the patterns was returning values with timestamps outside the requested time range. Closing

**Closed by gtk-grafana** 2024-07-01 18:13 UTC
Labels: bug, needs more info
