### ISSUE TITLE
Detected fields: warning notice when no fields available

### ISSUE THREAD

**Issue by matryer** [grafana/explore-logs#536] opened 2024-07-09 14:09 UTC
I think we can just have this as text on the page, or do what we do for other empty states explaining.

- [ ] Figure out what hint we can give people in this case

<img width="826" alt="image" src="https://github.com/grafana/explore-logs/assets/101659/5b70da0d-7f77-45ac-9a97-25990b31f921">

**Comment by zizzpudding** [comment] 2024-07-10 16:08
Is there a way to disable or remove the tab if there are no items under it?  

In Patterns we had a message to setup patterns, but this is different.  If we can't detect fields, we shouldn't show the tab.

**Comment by gtk-grafana** [comment] 2024-07-11 12:43
Duplicate of https://github.com/grafana/explore-logs/issues/529

**Comment by gtk-grafana** [comment] 2024-07-11 12:44
Actually no, need more coffee

**Closed** 2024-07-11 14:51 UTC
Labels: bug
